//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_School_Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignClass2
    {
        public int A_Id { get; set; }
        public int T_Id { get; set; }
        public int C_Id { get; set; }
    
        public virtual classes1 classes1 { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
